# Generated by Django 3.2.16 on 2023-01-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar',
            field=models.CharField(default=1344244, max_length=20, verbose_name='aadhar'),
            preserve_default=False,
        ),
    ]
